### ISSUE TITLE
How to install ssh on Termux?

### ISSUE THREAD

**Issue by Jezwin** [Auxilus/Auxilus.github.io#1]
pkg install openssh shows error.

**Comment by Auxilus** [comment]
`apt install openssh`

**Comment by Auxilus** [comment]
open issue at https://github.com/termux/termux-packages

**Comment by HashiSlashi** [comment]
Bro please help I am not getting direct link the space is empty

**Comment by V3rB0se** [comment]
> Bro please help I am not getting direct link the space is empty
openssh isnt related to Auxilus. its a package of termux.

**Comment by idemnos** [comment]
Solved! Use apt instead of apk. Cheers!
Have the same issue. 
`pkg install openssh`
Shows 

> Unable to locate package openssh

The same for PHP package.

**Comment by sammydangers** [comment]
I have the same problem I suppose.
SSH
OpenSSH is all the same. 


Checking availability of current mirror: bad
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: bad
[*] https://grimler.se/termux-packages-24: ok
[*] https://main.termux-mirror.ml: bad
[*] https://termux.mentality.rip/termux-packages-24: ok
Picking mirror: https://termux.mentality.rip/termux-packages-24
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package openssh
$

**Comment by Kartik1473** [comment]
> I have the same problem I suppose.
> SSH
> OpenSSH is all the same.
> 
> Checking availability of current mirror: bad
> Testing the available mirrors:
> [_] https://dl.bintray.com/termux/termux-packages-24: bad [_] https://grimler.se/termux-packages-24: ok
> [_] https://main.termux-mirror.ml: bad [_] https://termux.mentality.rip/termux-packages-24: ok
> Picking mirror: https://termux.mentality.rip/termux-packages-24
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package openssh
> $

Try apt-get install openssh

**Comment by rofrol** [comment]
if there is error during upgrade that repository is disabled

```
$ termux-change-repo
# select Grimler repo
# then run again
$ pkg upgrade
```

>Don't use apt or apt-get, but use pkg instead https://github.com/termux/termux-app/issues/1802#issuecomment-716877183

https://stackoverflow.com/questions/67647518/i-want-to-ask-how-to-fix-this-termux-repository/68881710#68881710

**Comment by ghost** [comment]
Hi 

> select

I tried this but I got this ┌─────────────termux-change-repo───────────────┐        │ Which repositories do you want to edit?      │
   │ Select with space.                           │        │ ┌──────────────────────────────────────────┐ │
   │ │ [*] Main repository     termux-packages  │ │        │ │ [ ] Game repository     game-packages    │ │
   │ │ [ ] Science repository  science-packages │ │        │ │

No grimler repo. Any help?

**Comment by rofrol** [comment]
@Blogher Use Termux from F-Droid https://stackoverflow.com/questions/67647518/i-want-to-ask-how-to-fix-this-termux-repository/68881710#68881710

or correct mirrors manually https://github.com/termux/termux-packages/wiki/Package-Management#package-command-errors

**Comment by Dannyblazer** [comment]
> Hi 
> 
> > select
> 
> I tried this but I got this ┌─────────────termux-change-repo───────────────┐        │ Which repositories do you want to edit?      │
>    │ Select with space.                           │        │ ┌──────────────────────────────────────────┐ │
>    │ │ [*] Main repository     termux-packages  │ │        │ │ [ ] Game repository     game-packages    │ │
>    │ │ [ ] Science repository  science-packages │ │        │ │
> 
> No grimler repo. Any help?

It's under the [*] Main Repo

**Comment by Kishanhacks** [comment]
Hello friends I am facing a problem. On fake root on termux I can't install openssh Pkg there show unable to locate pakage openssh.

 How can I solve it??
