### ISSUE TITLE
Package postgresql-contrib was be removed from offical termux repo

### ISSUE THREAD

**Issue by myfreess** [Auxilus/Auxilus.github.io#2]
[~/workdir]$ apt search postgresql
Sorting... Done
Full Text Search... Done
php-pgsql/stable 7.2.10 arm
  PostgreSQL modules for PHP

postgresql/stable 10.5-1 arm
  Object-relational SQL database

postgresql-dev/stable 10.5-1 arm
  Development files for postgresql

**Comment by Auxilus** [comment]
hmm, I don't really get what is the issue...
