### ISSUE TITLE
public key not available

### ISSUE THREAD

**Issue by diehard88** [Auxilus/Auxilus.github.io#4]
Err:3 https://Auxilus.github.io termux InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A02DAB86B7A6E4BE
Reading package lists... Done

**Comment by Auxilus** [comment]
hi, sorry but the repository is not currently up.

**Comment by Auxilus** [comment]
hi, sorry but the repository is not currently up.

**Comment by diehard88** [comment]
thank you.
