### ISSUE TITLE
Metasploit deb file needs update

### ISSUE THREAD

**Issue by elogada** [Auxilus/Auxilus.github.io#5]
Msf just got updated to msf5. I know that the msf tracker has explicitly stated that msf is not supported for Termux, but it works, at least, for me.

**Bug Summary**: msf deb file needs update
**Suggested Fix**: download the deb file, and post it here

Also I highly suggest that the old msf deb not be removed totally.
If this were to happen, one would need another installation script (maybe) should they decide to revert to msf 4.7

**Bug Summary**: old installation script would not install the new deb file
**Suggested Fix**: make a different autoinstaller for the new one (old as backup)

**Comment by Auxilus** [comment]
Hi,
metasploit package is now added to the [official unstable repo](github.com/termux/unstable-packages). You can install it with `pkg install unstable-repo && pkg install metasploit`

I'll update the installation script here to msf5 once I'm done testing it.

**Comment by elogada** [comment]
Alright, thanks @Auxilus. I'll keep the thread open, to serve as a reference. Will close once the msf5 installer is live.

**Comment by Auxilus** [comment]
@elogada I've updated metasploit-framework to 5.0.13, it's now available in unstable-repo for installation.

**Comment by Auxilus** [comment]
I also think that there is any point keeping a separate script here, as the package is available in termux repo, what's your opinion on that?

**Comment by elogada** [comment]
As a bug bounty hunter, I say keep it. Sources like Wayback Machine might reference to the file.

Plus there's really no harm in it, unless, say, it were to be updated

Closing thread
